from task_1 import line_algorytms
from task_2 import triangle
from task_3 import a_branching
from task_3 import b_branching
from task_4 import choise
from task_5 import loop_measures
from task_6 import the_sum_and_the_product
from task_7 import endless_sum
from task_8 import loop_data_search
from task_9 import one_dimencional_arrs
from task_10 import arrs_hard_data_search
